#!/bin/bash
status=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/state:/ {print $2}')
percentage=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage:/ {print substr($2, 1, length($2)-1)}')
toprint=""

if [ $percentage -ge 98 ]; then
    if [ $status != 'discharging' ]; then
        toprint=""
    else
        toprint=""
    fi
elif [ $percentage -ge 90 ]; then
    if [ $status != 'discharging' ]; then
        toprint=""
    else
        toprint=""
    fi
elif [ $percentage -ge 75 ]; then
    if [ $status != 'discharging' ]; then
        toprint=""
    else
        toprint=""
    fi
elif [ $percentage -ge 60 ]; then
    if [ $status != 'discharging' ]; then
        toprint=""
    else
        toprint=""
    fi
elif [ $percentage -ge 40 ]; then
    if [ $status != 'discharging' ]; then
        toprint=""
    else
        toprint=""
    fi
elif [ $percentage -ge 25 ]; then
    if [ $status != 'discharging' ]; then
        toprint=""
    else
        toprint=""
    fi
elif [ $percentage -ge 10 ]; then
    if [ $status != 'discharging' ]; then
        toprint=""
    else
        toprint=""
    fi
else
    if [ $status != 'discharging' ]; then
        toprint=""
    else
        toprint="%{F#ff5555}%{F-}"
    fi
fi

echo "%{T8}$toprint%{T-} "
    
