#!/bin/bash
status=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/state:/ {print $2}')
percentage=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | awk '/percentage:/ {print substr($2, 1, length($2)-1)}')
toprint=""

if [ $status != 'discharging' ]
then
    toprint=""
elif [ $percentage -ge 90 ]
then
    toprint=""
elif [ $percentage -ge 65 ]
then
    toprint=""
elif [ $percentage -ge 40 ]
then
    toprint=""
elif [ $percentage -ge 6 ]
then
    toprint=""
else
    toprint=""
fi

echo $toprint $percentage%
    
