#!/bin/bash
e180-rdb () {
	cd ~/projects/e180/braindate-api
	docker-compose stop
	docker-compose down -v
	docker-compose up -d --build
	docker-compose run --rm -e DJANGO_SKIP_ENTRYPOINT_ACTIONS=0 -e DJANGO_SKIP_ENTRYPOINT_COMPILEMESSAGES=0 api bash -c 'python manage.py populate_db'
}

alias dcd="docker-compose down"
alias dcu="docker-compose up -d"
alias dcdu="docker-compose down && docker-compose up -d"
alias pym="python manage.py"
