#!/bin/sh
playerctl -p youtubemusic metadata -f {{playerName}} 2>/dev/null | grep -v mopidy >/dev/null && echo %{A1:playerctl -p youtubemusic previous:}玲%{A} %{A1:playerctl -p youtubemusic play-pause:}$(playerctl -p youtubemusic status 2>/dev/null | grep Playing >/dev/null && echo '' || echo '契')%{A} %{A1:playerctl -p youtubemusic next:}怜%{A} "%{T1}  | %{T-} %{T4}%{T-}";
echo "%{T4}%{T-}" ;